[theme]
# Primärfarbe (aus dem Bild, dunkles Grau)
primaryColor = "#696969"

# Hintergrundfarbe (aus dem Bild, sehr helles Grau/Weiß)
backgroundColor = "#F8F8F8"

# Sekundäre Hintergrundfarbe (aus dem Bild, dunkleres Grau)
secondaryBackgroundColor = "#D3D3D3"

# Textfarbe (fast Schwarz für Kontrast auf hellem Hintergrund)
textColor = "#222222"

# Schriftart (aus dem Bild, Comfortaa)
font = "sans serif" # Streamlit unterstützt keine custom fonts, daher als Näherungswert "sans serif"

[client]
# Deaktiviert das Hamburger-Menü oben rechts
toolbarMode = "minimal"

[runner]
# Deaktiviert das schnelle Neuladen (sollte im Produktivbetrieb deaktiviert sein)
fastReruns = false

[server]
# CORS-Einstellungen (anpassen, falls nötig)
enableCORS = false

# XSRF-Schutz-Einstellungen (aktivieren, wenn nötig)
enableXsrfProtection = false