[ui]
showSidebarNavigation = true

[browser]
toolbarMode = "minimal"

[theme]
# Primary color (Dark Grey)
primaryColor = "#696969"

# Background color (Very light grey/White)
backgroundColor = "#F8F8F8"

# Secondary background color (Grey)
secondaryBackgroundColor = "#D3D3D3"

# Text color (Almost Black)
textColor = "#222222"

# Font
font = "sans serif"

[client]
# Hide the menu button
toolbarMode = "minimal"

[runner]
# Disable fast reruns during development
fastReruns = false

[server]
# CORS settings (adjust if needed)
enableCORS = false

# XSRF protection (enable if needed)
enableXsrfProtection = false